// ANGULAR/ANGULAR-ParentToChild/src/app/parent/parent.ts
import { Component } from '@angular/core';
import { ChildComponent } from '../child/child';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-parent',
  imports: [ChildComponent, FormsModule],
  templateUrl: './parent.html',
  styleUrl: './parent.css'
})
export class ParentComponent {
  data: string = '';
  show: string = '';

  sendData(): void {
    this.data = this.show;
  }

  loadData(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.show = target.value;
  }
}

// REACT/ParentToChild/src/Parent.jsx
import React, { useState } from 'react';
import Child from './Child';
const Parent = () => {
  const [data, setData] = useState('');
  const [show, setShow] = useState('');
  function sendData() {
    setData(show);
  }
  function loadData(e) {
    setShow(e.target.value);
  }
  return (
    <>
      <Child sendData={data} />
      <input onChange={(e) => loadData(e)} />
      <button onClick={sendData}>Click</button>
    </>
  );
};
export default Parent;
